spring:
  data:
    redis:
      host: 194.233.91.140
      port: 16379
      timeout: 30000
      user: default
      #      password: CF@2025
      ssl:
        enabled: false

keycloak:
  url: https://key-aim.cambofreelance.com
  realm: cambofreelance.dev
  audience-client-id: KPS_GAME
  audience-client-secret: yCygkPDxcPp3qtH0lGtBHvFhXKYBxTm1
  admin-cli-client-id: authentication-client
  admin-cli-client-secret: wJzYfm093CKXwCmzScq1Qm6IAVNCcoLz
  enable: Y