server:
  port: 8081
spring:
  application:
    name: msa-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/common/
            - classpath:config/api-gateway/
            - classpath:config/authentication-server/
            - classpath:config/lottery/
            - classpath:config/document/
management:
  endpoints:
    web:
      exposure:
        exclude: '*'