server:
  port: 8081
spring:
  application:
    name: msa-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/user-service/
            - classpath:config/api-gateway/
            - classpath:config/authentication/
            - classpath:config/report-service/
management:
  endpoints:
    web:
      exposure:
        exclude: '*'