server:
  port: 2514

spring:
  application:
    name: admin-service
  datasource:
    password: CF@@2025
    url: jdbc:postgresql://161.97.138.103:12009/cf_uat_db
    username: postgres
  jpa:
    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: 161.97.138.103
      port: 6379
      timeout: 30000
      password: CF@2025
      ssl:
        enabled: false

  spring:
    zipkin:
      base-url: http://161.97.138.103:9411

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  upload:
    client:
      path: /image/**
    server:
      path: /opt/cambofreelance/upload/images/

springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  packagesToScan: com.cambofreelance.authenticationservice.controllers
  pathsToMatch: /**
  swagger-ui:
    path: /openapi/swagger-ui.html
authentication:
  jwtExpiration: 300000
  jwtRefreshExpiration: 86400000
  jwtSecret: ebe8910a-08c0-11ed-861d-0242ac120002
