server:
  port: 2512

spring:
  application:
    name: admin-service
  datasource:
    password: CF@@2025
    url: jdbc:postgresql://161.97.138.103:12009/cf_uat_db
    username: postgres
  jpa:
    hibernate:
    #      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: 161.97.138.103
      port: 6379
      timeout: 30000
      password: CF@2025
      ssl:
        enabled: false

  spring:
    zipkin:
      base-url: http://161.97.138.103:9411

logging:
  file:
    path: /uat/logs/${spring.application.name}
    name: ${logging.file.path}/${POD_NAME:my-app}.log

  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    file: "[%d] [%t] %-5level [${spring.application.name},%X{traceId},%X{spanId},%X{activityid}] %logger{36} - %msg%n"
    console: "[%d] [%t] %-5level [${spring.application.name},%X{traceId},%X{spanId},%X{activityid}] %logger{36} - %msg%n"

  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${POD_NAME:my-app}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 5GB

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  upload:
    client:
      path: /image/**
    server:
      path: /opt/uat/upload/images/

springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  packagesToScan: com.cambofreelance.adminservice.controllers
  pathsToMatch: /**
  swagger-ui:
    path: /openapi/swagger-ui.html
authentication:
  jwtExpiration: 300000
  jwtRefreshExpiration: 86400000
  jwtSecret: ebe8910a-08c0-11ed-861d-0242ac120002

storage:
  redis:
    key-response-code: key-response-code-uat
    key-api-route: key-api-route-uat
    key-application-feature: key-application-feature-uat