server:
  port: 25012

spring:
  application:
    name: lottery-server
  datasource:
    url: jdbc:postgresql://194.233.91.140:2017/dev_lottery
    username: postgres
    password: CAMBO@@2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: false
    locations: classpath:db/migration
    placeholders:
      defaultSchema: public
    rollback-locations: classpath:db/rollback
  cache:
    type: redis

  data:
    redis:
      host: 194.233.91.140
      port: 16379
      timeout: 30000
      user: default
      #      password: CF@2025
      ssl:
        enabled: false
      repositories:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://key-aim.cambofreelance.com/realms/cambofreelance.dev

keycloak:
  url: https://key-aim.cambofreelance.com
  realm: cambofreelance.dev
  audience-client-id: KPS_GAME
  audience-client-secret: yCygkPDxcPp3qtH0lGtBHvFhXKYBxTm1
  admin-cli-client-id: authentication-client
  admin-cli-client-secret: wJzYfm093CKXwCmzScq1Qm6IAVNCcoLz

otel:
  exporter:
    otlp:
      endpoint: http://alloy.monitoring.svc.cluster.local:4317
      protocol: grpc
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    sampler:
      probability: 1.0

  service:
    name: keycloak-authentication-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh

logging:
  enable: true
  includeRequest: true
  includeRequestBody: true
  maskLogKey: maskingKey001,maskingkey001,masking-type-002 # its type is sensitive
  ignoreDefaultMaskingLogKey: ignoreMaskingKey001,ignoreMasking-type-002
  includeRequestHeader: true
  maxRequestBody: 1000 # its value is byte
  ignoreAntMatches: /abc,/zte-ba/**,/hiding-log # this value just example
  includeResponse: true
  includeResponseHeader: true
  maskResponseHeaderKey: maskingKey001,maskingkey001,masking-type-002 # its type isn't sensitive
  includeResponseBody: true
  maxResponseBody: 200 # its value is byte, the log size response

  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    console: "[%d] [%t] %-5level [${spring.application.name},%X{traceId},%X{spanId},%X{activityid}] %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan: com.cambofreelance.keycloakauthenticationserver.controllers
  paths-to-match: /**
  swagger-ui:
    path: /auth/openapi/swagger-ui.html

storage:
  redis:
    key-response-code: type-response-code-authentication

aes-cipher:
  gcm:
    key: UsLHzxoYLfUZ6sFbPs906dWmf3tulwJs/MfMAvT8SLk=
    algorithm: AES/GCM/NoPadding
    iv: ZGRFq4ZfB20=
    key-size: 128

app-config:
  otp-expired: 120 # OTP expired in 2 min
  otp-limited-generate: 100 # OTP limited generate in 100 time
  password-policy: 8

applogger:
  enabled: true
  mode: PARTIAL


mail:
  host: smtp.gmail.com
  port: 587
  username: cambofreelance.dev@gmail.com
  password: The@2424
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
otp:
  expiration-minutes: 5
  limit-per-day: 10
  user-session-expiration-minutes: 30

authentication-service:
  url: http://auth-keycloak-service:25011
