server:
  port: 25011

spring:
  application:
    name: document-management-server
  datasource:
    url: jdbc:postgresql://194.233.91.140:2017/dev_document_db
    username: postgres
    password: CAMBO@@2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: false
    locations: classpath:db/migration
    placeholders:
      defaultSchema: public
    rollback-locations: classpath:db/rollback
  cache:
    type: redis

  data:
    redis:
      host: 194.233.91.140
      port: 16379
      timeout: 30000
      user: default
      #      password: CF@2025
      ssl:
        enabled: false
      repositories:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://key-aim.cambofreelance.com/realms/cambofreelance.dev

keycloak:
  url: https://key-aim.cambofreelance.com
  realm: cambofreelance.dev
  audience-client-id: CAMBO_FREELANCE
  audience-client-secret: wAQozfxCQMuLoT1ONpZzwenbM6FM2fpQ
  admin-cli-client-id: authentication-client
  admin-cli-client-secret: wJzYfm093CKXwCmzScq1Qm6IAVNCcoLz
  use-entitlements: false # false: check specific permission
  permission-resource-format: id # perm: resourceId#scope
  include-resource-name: true # check authorization by provide resourceName, then will call to get resourceId
  http:
    connect-timeout-ms: 10000
    response-timeout-ms: 30000
  retry:
    maxRetries: 3
    delayMs: 500
  cache:
    prefix: keycloak
    expiry-safety-slack: 60s # subtract from provider expires_in
    default-ttl: 1h
    revoke:
      key: revoke
      max-ttl: 12h
    authorization:
      enabled: false
      key: authorizations
      token-ttl: 5m
    client-credential:
      enabled: false
      key: client_credentials
    resource:
      enabled: false
      key: resources

otel:
  exporter:
    otlp:
      endpoint: http://alloy.monitoring.svc.cluster.local:4317
      protocol: grpc
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    sampler:
      probability: 1.0

  service:
    name: document-management-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh

logging:
  enable: true
  includeRequest: true
  includeRequestBody: true
  maskLogKey: maskingKey001,maskingkey001,masking-type-002 # its type is sensitive
  ignoreDefaultMaskingLogKey: ignoreMaskingKey001,ignoreMasking-type-002
  includeRequestHeader: true
  maxRequestBody: 1000 # its value is byte
  ignoreAntMatches: /abc,/zte-ba/**,/hiding-log # this value just example
  includeResponse: true
  includeResponseHeader: true
  maskResponseHeaderKey: maskingKey001,maskingkey001,masking-type-002 # its type isn't sensitive
  includeResponseBody: true
  maxResponseBody: 200 # its value is byte, the log size response

  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
    console: "[%d] [%t] %-5level [${spring.application.name},%X{traceId},%X{spanId},%X{activityid}] %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan: com.cambofreelance.keycloakauthenticationserver.controllers
  paths-to-match: /**
  swagger-ui:
    path: /documents/openapi/swagger-ui.html

storage:
  redis:
    key-response-code: type-response-code-authentication

aes-cipher:
  gcm:
    key: UsLHzxoYLfUZ6sFbPs906dWmf3tulwJs/MfMAvT8SLk=
    algorithm: AES/GCM/NoPadding
    iv: ZGRFq4ZfB20=
    key-size: 128

app-config:
  otp-expired: 120 # OTP expired in 2 min
  otp-limited-generate: 100 # OTP limited generate in 100 time
  password-policy: 8

applogger:
  enabled: true
  mode: PARTIAL


mail:
  host: smtp.gmail.com
  port: 587
  username: cambofreelance.dev@gmail.com
  password: The@2424
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
otp:
  expiration-minutes: 5
  limit-per-day: 10
  user-session-expiration-minutes: 30

# src/main/resources/application-local.yml
digitalocean:
  spaces:
    endpoint:   https://sgp1.digitaloceanspaces.com
    region:     sgp1
    bucket:     mowram.misstorage
    access-key: DO00C26786AJ7TX7QL9Y
    secret-key: zWQAbpl8obhPxlgCzWDWC4tcB246zRGq7H3wG2b+iWQ
    presign-expiry-minutes: 15